# https://github.com/phips28/gh-action-bump-version
# in commit use #major or #minor or #patch (default) to bump the version

name: 'release version'
on:
    push:
        branches:
            - 'development'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
    tagged-release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  node-version: 20
            - name: Get package version
              id: package_version
              run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV
            - name: Get commit message
              id: commit_message
              run: echo "message=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
            - name: Create release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GIT_TOKEN }}
                  automatic_release_tag: '${{ env.version }}'
                  prerelease: false
                  files: ./*
                  body: ${{ env.message }}
